Repository getgauge/gauge-vscode, pull requests merged in 2019-01, with the labels that each got.

#329 Vscode java debug support
  package.json
  src/execution/debug.ts
  src/init/projectInit.ts
  src/util.ts
Labels: cla-signed, ready

#330 Fix for, #319
  src/execution/gaugeExecutor.ts
Labels: ready

#337 Fix for classpath issue in Gauge-Java project.
  package-lock.json
  package.json
  src/config/gaugeProjectConfig.ts
  src/gaugeVersion.ts
  src/gaugeWorkspace.ts
Labels: cla-signed, ready

#338 fixed show last execution report for maven project.
  package-lock.json
  src/execution/gaugeExecutor.ts
Labels: cla-signed, ready

#341 Handling mvn command for windows #331 #333
  src/constants.ts
  src/init/projectInit.ts
  src/util.ts
Labels: cla-signed, ready

#343 Stopping the current execution.
  package.json
  src/execution/debug.ts
  src/execution/gaugeExecutor.ts
Labels: cla-signed, ready

#345 Replace getting started page with welcome notification.
  package.json
  src/constants.ts
  src/extension.ts
  src/pages/provider.ts
  src/pages/welcome.ts
  src/welcomeNotifications.ts
  test/pages/welcome.test.ts
Labels: cla-signed

#348 Accumulate broken stdout line from child process into one complete line
  src/execution/gaugeExecutor.ts
Labels: cla-signed, ready
